version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/    
  - source: ./
    destination: /etc/testapp/
file_exists_behavior: RETAIN

hooks:

  BeforeInstall:
   - location: /scripts/create_timed_backup.sh
     timeout: 300
     runas: root
   - location: /scripts/indexbackup.sh
     timeout: 300
     runas: root   
