version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
    overwrite: yes
  - source: ./
    destination: /etc/testapp/
    overwrite: yes
file_exists_behavior: OVERWRITE

hooks:

  BeforeInstall:
   - location: /scripts/createbackup.sh
     timeout: 300
     runas: root
   - location: /scripts/indexbackup.sh
     timeout: 300
     runas: root   